# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('established', models.DateTimeField(verbose_name='date established')),
                ('emp_cnt', models.IntegerField()),
            ],
        ),
    ]
